import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { type ReactNode } from "react";

import "../styles/globals.css";
import { cn } from "@/utils";
import { DefaultLayout } from "@/components/layouts/DefaultLayout";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-poppins",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: { children: ReactNode; modal: ReactNode }) {
	return (
		<html lang="pl">
			<body className={cn("flex min-h-screen flex-col", poppins.variable)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<DefaultLayout>{children}</DefaultLayout>
				</ThemeProvider>

				{modal}
			</body>
		</html>
	);
}
