import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { type ReactNode } from "react";

import "../styles/globals.css";
import { Providers } from "./providers";
import { DefaultLayout } from "@/components/layouts/DefaultLayout";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-poppins",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: { children: ReactNode; modal: ReactNode }) {
	return (
		<html lang="pl">
			<body className={poppins.variable}>
				<Providers>
					<DefaultLayout>{children}</DefaultLayout>
				</Providers>

				{modal}
			</body>
		</html>
	);
}
